ponnamkarthik/FlutterToast

- CHANGELOG.md
- pubspec.yaml
After the update, the pluginClass name was change but not in the pubspec.
lib/generated_plugin_registrant.dart:22:60: Error: Getter not found: 'FluttertoastWebPlugin'.
FluttertoastWebPlugin.registerWith(registry.registrarFor(FluttertoastWebPlugin));
> fix pubspec web pluginClass Name

- ios/Classes/FluttertoastPlugin.m
The Toast Message will now appear above all views as its directly added to the top most view of the window for IOS
> Fixed IOS Toast message shown below the keyboard if open or other views

- android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt
Calling `cancel` before `showToast` makes apps crash with the following Kotlin exception message: `lateinit property mToast not initialized`.
In my apps, I needed to "cancel" any pending Toasts (before they disappear on their own) prior to displaying new ones, and this is why I stumbled upon this particular corner case. Rather than explicitly handling that very first interaction with FlutterToast, I thought it would be more useful to just do nothing if  `cancel` is called without a prior call to `showToast`.
Feel free to close this PR if you think it doesn't make sense.
Thanks!
> Safely call 'cancel' on Android even if lateinit property 'mToast' had not been initialized beforehand

- android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt
The `gradientDrawable` corner settings were unstable, so I changed `PorterDuff.Mode` to use the corners of the inflated layout.
issue #225 
|before|after|
|------|-----|
|<img src=https://user-images.githubusercontent.com/1748326/96360285-c4b52e80-1156-11eb-8a7b-de78bca0a97a.gif  width=50%>|<img src=https://user-images.githubusercontent.com/1748326/96360288-c7b01f00-1156-11eb-9f54-83c800e75114.gif  width=50%>|
> Android Fixed Circular borders are gone (#225)

- lib/fluttertoast_web.dart
When using the newline character(`\n`), `showToast` is crashed with printing the below error.
<details>
<summary>Error log</summary>
```
Uncaught SyntaxError: Invalid or unexpected token
at HTMLHeadElement.[dartx.append] (html_dart2js.dart:23451)
at html$._ChildrenElementList._wrap.add (html_dart2js.dart:11765)
at fluttertoast_web.FluttertoastWebPlugin.new.addHtmlToast (fluttertoast_web.dart:100)
at fluttertoast_web.FluttertoastWebPlugin.new.showToast (fluttertoast_web.dart:47)
at fluttertoast_web.FluttertoastWebPlugin.new.handleMethodCall (fluttertoast_web.dart:20)
at handleMethodCall.next (<anonymous>)
at runBody (async_patch.dart:84)
at Object._async [as async] (async_patch.dart:123)
at fluttertoast_web.FluttertoastWebPlugin.new.handleMethodCall (fluttertoast_web.dart:17)
at …
```
> Fix crash with text include newline character(\n) on web

- android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt
fix for error that says `Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type View?` on Android
> fix: #298 safe call Android view object

- android/build.gradle
Following as Jcenter shutting down.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
> Migrate from Jcenter to Maven Central

- ios/fluttertoast.podspec
Fix #332
Suggested solution is obtained from https://github.com/CocoaPods/CocoaPods/issues/10104#issuecomment-704862852
This issue has been found since Flutter 2.5.0.
> Unable to launch app in iOS simulators on Apple Silicon Machines (M1 Mac) in Flutter 2.5.0

- lib/fluttertoast.dart
I found a bug that when `removeCustomToast()` and `showToast()` are executed during an animation that is made to disappear by `hideIt`, it disappears immediately.
I have fixed this.
I am using deepL
Video before modification
https://user-images.githubusercontent.com/38094366/176593882-1aba0fe1-8c8c-4508-bca2-84a94d3ab513.mov
> Fix fadeDuration

- ios/fluttertoast.podspec
This change fixed https://github.com/ponnamkarthik/FlutterToast/issues/388 for me.
To get this line I have created a new empty Flutter plugin using Android Studio. Then the fluttertoast.podspec file contained this line instead of the lines that were in the FlutterToast project. After replacing them, the scrolling works fine now.
> Bug fix for running on M1 iOS simulator.

- example/pubspec.lock
- pubspec.lock
- pubspec.yaml
the project used BuildContext.mounted and Overlay.maybeOf which is only available in version 3.7, so add environment restriction in pubspec.
https://github.com/ponnamkarthik/FlutterToast/issues/417
> Add environment restriction in pubspec

- lib/fluttertoast_web.dart
In Flutter it is possible to customize the location that assets will be loaded from  (e.g. using `assetBase` meta tag or providing this property to engine initializer directly)
Current solution assumes that js script and css file are always under `<rootUrl>/assets/` directory, which is not true if `assetBase` is used. So in the current PR I use `getAssetUrl` utility provided by Flutter that respects `assetBase`
https://github.com/flutter/engine/blob/942909b77001b4904e26aa29e3cac63345108a0a/lib/web_ui/lib/ui_web/src/ui_web/asset_manager.dart#L76-L81
> fix(web): get css & js urls using flutter utility

- README.md
This should fix issue #435 when the package is updated for the [pub.dev](https://pub.dev/packages/fluttertoast) site. A trailing whitespace caused the table to be incorrectly formatted in the dart md environment (pub.dev) but is corrected rendered in the GitHub page.
> Fixed Trailing Whitespace in table 

- lib/fluttertoast_web.dart
Hi.
I develop flutter web with use the FlutterToast plugin.
but in the file fluttertoast_web.dart the deprecated API. (Same the [issue](https://github.com/ponnamkarthik/FlutterToast/issues/485))
so i change the Deprecated API. 
```
import 'dart:ui' as ui; -> import 'dart:ui_web' as ui;
webOnlyAssetManager -> assetManager
```
> [Fix] Deprecated webOnlyAssetManage -> assetManager

- ios/fluttertoast.podspec
Fixes https://github.com/ponnamkarthik/FlutterToast/issues/463
Prior to https://github.com/ponnamkarthik/FlutterToast/pull/405, this line matched the [flutter plugin template](https://github.com/flutter/flutter/blob/140edb9883122e335ecb99416934c9436d6a6d10/packages/flutter_tools/templates/plugin_ffi/ios.tmpl/projectName.podspec.tmp)
```
`s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386' }` 
```
In #405, `arm64` was added to `EXCLUDED_ARCHS[sdk=iphonesimulator*]` to work around dependencies missing `arm64` slices for simulator, but that change is no longer necessary: https://github.com/CocoaPods/CocoaPods/issues/10104#issuecomment-704916617.
In #425, the line was changed to add `VALID_ARCHS`, which is a deprecated build setting …
> Removing VALID_ARCHS from `pod_target_xcconfig` in iOS podspec

- example/pubspec.lock
- lib/fluttertoast_web.dart
- pubspec.lock
- pubspec.yaml
This PR addresses the following issue:  #498
> Migrating dart:html to package:web

- example/pubspec.lock
- lib/fluttertoast.dart
The _FToastHolder which returns the Overlay widget with a specific directionality [Directionality.ltr] prevents the app from mirroring when we switch the localization to  a new locale that uses [Directionality.rtl] and after removing it the issue fixes
> Fix Directionality issue

- README.md
- android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt
- lib/fluttertoast.dart
This adds an optional parameter `fontAsset` to the `showToast` method that allows to apply a custom font from the Flutter app `assets` folder to the text of the toast on Android below [API level `30` (Android R)](https://developer.android.com/reference/android/os/Build.VERSION_CODES#R) where we have access to the `TextView`. Credit for the change goes to @nt4f04uNd. We have been using a fork with these changes for the past year.
[Usage example:](https://github.com/nt4f04uNd/sweyer/blob/86ca448fd4a396031b444f30fca4df3189b71961/lib/widgets/show_functions.dart#L25-L34)
```dart
Fluttertoast.showToast(
msg: msg,
fontAsset: 'assets/path/to/some-font.ttf',
);
```
| Normal toast | Toast with comic sans font |
|--------|--------|
| `Fluttertoast.showToast(msg: msg);` | `Fluttertoast.showToast(msg: …
> Allow to use a font asset on Android

- lib/fluttertoast_web.dart
Fixes #528
There was following compile-time error : 
Error: A value of type 'JSString' can't be assigned to a variable of type 'String'.
It is fixed by adding .toString();
> Fix: #528 Error: A value of type 'JSString' can't be assigned to a variable of type 'String'. 

- lib/fluttertoast.dart
There is a current issue here:
https://github.com/ponnamkarthik/FlutterToast/issues/547
This fixes it.
```
if (backgroundColor == null && !kIsWeb && Platform.isIOS) {
backgroundColor = Colors.black;
}
if (textColor == null && !kIsWeb && Platform.isIOS) {
textColor = Colors.white;
}
```
The `!kIsWeb` check ensures that the `Platform.isIOS` check is only executed on mobile devices and not on the web platform. This prevents a crash that would occur if `Platform.isIOS` is called on the web.
> Fix web support by adding !kIsWeb check to Platform check

- android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt
- Remove debug log statement that was causing D/KARTHIK spam in Android logs
- Only call setGravity() on custom toasts with background color to avoid Android API 30+ warnings on text toasts
> fix: remove debug log spam and setGravity warnings

- lib/fluttertoast.dart
Hi!
We see a small number of error reports caused by unmounted context at the time `FToast.removeCustomToast` is called. 
We have a Flutter app integrated into the native app and this is what happens:
1. We show a toast
2. User pops the page and the whole flutter app is closed (and thus the context is unmounted)
3. FToast calls `removeCustomToast` on timer to close the toast that is shown
4. `_showOverlay` is called that tries to get the `Overlay`, but the context is unmounted
5. The error is thrown
The straightforward fix would be to just check whether the context is mounted and handle this edge case. However, I see that there is already code in place to do that, but it is commented out by this commit https://github.com/ponnamkarthik/FlutterToast/commit/5c1dd53eef3b7f8ad4fbe7318e9facfaf62 …
> fix: put back context.mounted check
