ios/Classes/FluttertoastPlugin.m, ios/fluttertoast.podspec, lib/fluttertoast.dart, pubspec.yaml
@PonnamKarthik  Please Check it
=> fix ios run error

android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.kt
A single instance of toast is used instead of a non single instance.
Fix the problem of incorrect background color.
=> android toast instance, toast background color

android/build.gradle, android/src/main/java/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.java, example/lib/main.dart, ios/Classes/FluttertoastPlugin.m, lib/fluttertoast.dart
Here's what I did:
- Instead of hex strings, I changed the API to use the native `dart:ui` `Color` class, which simply encapsulates 32-bit integers. (Sorry for the breaking change, but I think this is more ideomatic for use with Flutter.)
- Fixed colors on iOS (and formatted Objective-C using AppCode).
- Made necessary changes to Android plugin to match iOS. (..a bit of code formatting here as well, removed unused imports, etc.)
Should fix #30, #25, and #13.
=> A few fixes and improvements

ios/Classes/FluttertoastPlugin.m
=> fix issue 55

ios/Classes/UIView+Toast.h, ios/Classes/UIView+Toast.m
fixed:Toast can be displayed in order on iOS
=> Fixed iOS queue display

android/build.gradle, android/src/main/java/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.java, example/android/app/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties
These dependencies caused conflicts used with various Google Flutter plugins.
=> Remove legacy dependencies

ios/Classes/FluttertoastPlugin.m
=> fix the toast show in key window problem

android/src/main/java/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.java, android/src/main/res/layout/toast_custom.xml
Optimized the custom layout of Android Toast, using GradientDrawable to set the style.
=> Optimized the custom layout of Android Toast

CONTRIBUTING.md
This will help you in evaluation of contribution guidelines. It shall also help the contributors in understanding how to contribute since most people do not know how to contribute to the open source
=> Created Contributors Guidelines

android/src/main/java/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.java
This is a bug for honor devices when show Toast not in main thread.
I have test it in honor device.
=> bug fix (Toast invisable on huawei honor device )

ios/Classes/FluttertoastPlugin.m
This pull request should fix #218.
=> Should fix #218.

lib/fluttertoast.dart
Added new option for ToastGravity called SNACKBAR which renders toast message much like a SnackBar widget does.
=> Added new option for ToastGravity called SNACKBAR.

lib/fluttertoast.dart
This PR just improves the English grammar of the main method of the library
=> Fix some documentation grammar

lib/fluttertoast.dart
solve the background color and font color problem in latest version.  (#328)
=> fixing #328

android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt
Toast doesn't shows up the correct background  color on android 11
=> Toast doesn't shows up the correct background

lib/fluttertoast.dart
Used null aware operator "?" to avoid crash
=> Fixed issue # 338

android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt
=> Fixed issue #340

lib/fluttertoast.dart
Hey @ponnamkarthik
Thank you for your awesome package which provide a possibility to show different beautiful messages to user!
I found some small problems with safety in FToast and tried to improve it. Please, check the result and leave feedback about PR possibilities.
Best regards, Alex
=> FToast improvements to provide safer usage

ios/fluttertoast.podspec
=> support M1

lib/fluttertoast.dart
IgnorePointer: Allows the toast to be tapped through
isDismissable: Dismisses toast on tap
=> Added IgnorePointer and isDismissable features to context toast

example/android/build.gradle, example/lib/main.dart, example/lib/toast_context.dart
=> Fixed center problem of buttons.

android/build.gradle, example/android/app/build.gradle
Change minSdkVersion from 21 to 19. Please see [android gradle build error](https://github.com/ponnamkarthik/FlutterToast/issues/475#issuecomment-1822274982).
Tested on android emulators(4.4(**19**), 12(**31**), 14(**34**) and android real device (13(**33**)).
=> build error fix

ios/Resources/PrivacyInfo.xcprivacy, ios/fluttertoast.podspec
This should address #481 for this package.
=> fix: privacy manifest

android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/FlutterToastPlugin.kt, android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt
…id version of the device is bigger than 30
=> bug fix - fix toast message error when android version is 31+

CHANGELOG.md, android/src/main/AndroidManifest.xml, android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/FlutterToastPlugin.kt, android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt, example/android/app/build.gradle, example/android/app/src/debug/AndroidManifest.xml, example/android/app/src/main/AndroidManifest.xml, example/android/app/src/profile/AndroidManifest.xml, example/android/build.gradle, example/android/gradle.properties, example/android/gradle/wrapper/gradle-wrapper.properties, example/pubspec.lock, pubspec.yaml
Fixes https://github.com/ponnamkarthik/FlutterToast/issues/523
Tested by building the FlutterToast example app with the changes in https://github.com/flutter/engine/pull/52022 applied.
=> Remove v1 embedding
